services:
  cups-exporter:
    build: .
    ports:
      - 9329:9329
    restart: unless-stopped
    user: 10001:10001
    volumes:
      - .:/usr/app
    command: python usr/app/cups_exporter.py --cups-port 6631
