permissions:
  id-token: write  # required to use OIDC authentication
  contents: read  # required to checkout the code from the repo
  
name: Promote to prod
on:
  workflow_dispatch:
  
# Only run one workflow at a time for a given branch.
# This blocks new staging images getting built and pushed
# while this workflow is running.
concurrency: ${{ github.ref_name }}

jobs:
  retag:
    name: Retag for prod
    if: ${{ github.ref_name == 'main' }}
    uses: tailsdotcom/actions/.github/workflows/retag-image.yml@main
    with:
      aws_role: 426105708615:role/ci-cups-exporter
      repository: infrastructure-engineering/cups-exporter
      environment: prod
